project:
  type: website
  output-dir: docs

website:
  title: |
    Advent of Code
  page-navigation: true
  navbar: 
    background: "#2aa198"
    foreground: "#ffffff"
  sidebar:
    title: "Solutions"
    style: docked
    type: dark
    alignment: right
    contents:
      - href: index.qmd
        text: "Home"
      - text: "----"
      - section: "2021"
        contents: 
          - 2021-01/day1.qmd
          - 2021-02/day2.qmd
          - 2021-03/day3.qmd
          - 2021-04/day4.qmd
          - 2021-05/day5.qmd
          - 2021-06/day6.qmd
          - 2021-07/day7.qmd
          - 2021-08/day8.qmd
          - 2021-09/day9.qmd
      - text: "----"
      - section: "2022"
        contents:
          - 2022-01/day1.Rmd
          - 2022-02/day2.Rmd
          - 2022-03/day3.Rmd
          - 2022-04/day4.Rmd
          - 2022-05/day5.Rmd
          - 2022-06/day6.Rmd
          - 2022-07/day7.Rmd
          - 2022-08/day8.Rmd
      - text: "----"
      - section: "2023"
        contents:
          - 2023-01/2023-01.qmd
      - text: "----"
      - section: "2024"
        contents:
          - 2024-01/day1.qmd
          - 2024-02/day2.qmd
          

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true
    mainfont: arial

execute:
  cache: true